name: docker-ci-pipeline
on:
  push:
    branches:
      - docker-ci

jobs:
  build-sysfoo-war:
    runs-on: ubuntu-latest

    steps:
      - name: Code Checkout or Code Clone
        uses: actions/checkout@v4

      - name: Run mvn test
        run: mvn test

      - name: Run mvn clean & mvn package
        run: mvn clean package

      - name: Run ls command
        run: ls -lrt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: sysfoo
          path: target/sysfoo.war
          
  build-sysfoo-docker:
    runs-on: ubuntu-latest
    needs: [build-sysfoo-war]
    
    steps:
      - name: Code Checkout or Code Clone
        uses: actions/checkout@v4
        
      - name: Login to Docker Hun
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      - name: Docker Build
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/sysfoo:v1
        
      -name: Docker Push
       run: docker push ${{ secrets.DOCKER_USERNAME }}/sysfoo:v1
